language: minimal
sudo: required
services:
  - docker
before_script:
  - tag="${TRAVIS_TAG:-latest}"
  - image_name="$(echo "${TRAVIS_REPO_SLUG}" | cut -d '/' -f 2)"
  - docker_org="actions"
script: .travis/build.sh $docker_org $tag $image_name
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  - provider: script
    script: .travis/deploy.sh $docker_org $tag $image_name
    on:
      branch: master
  - provider: script
    script: .travis/deploy.sh $docker_org $tag $image_name
    on:
      branch: master
      tags: true
env:
  - JAVA_TAG=8 JAVA_VERSION=8u192-jdk-7 MAJOR_VERSION=3 MINOR_VERSION=6 PATCH_VERSION=0 SHA256_SUM=6a1b346af36a1f1a491c1c1a141667c5de69b42e6611d3687df26868bc0f4637 BUILD_ARGS="JAVA_TAG JAVA_VERSION MAJOR_VERSION MINOR_VERSION PATCH_VERSION SHA256_SUM"
  - JAVA_TAG=11 JAVA_VERSION=11.0.1-jdk-7 MAJOR_VERSION=3 MINOR_VERSION=6 PATCH_VERSION=0 SHA256_SUM=6a1b346af36a1f1a491c1c1a141667c5de69b42e6611d3687df26868bc0f4637 BUILD_ARGS="JAVA_TAG JAVA_VERSION MAJOR_VERSION MINOR_VERSION PATCH_VERSION SHA256_SUM"
