language: minimal
sudo: required
services:
  - docker
before_script:
  - tag="${TRAVIS_TAG:-latest}"
  - image_name="$(echo "${TRAVIS_REPO_SLUG}" | cut -d '/' -f 2)"
  - docker_org="actions"
script: .travis/build.sh $docker_org $tag $image_name
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  - provider: script
    script: .travis/deploy.sh $docker_org $tag $image_name
    on:
      branch: master
  - provider: script
    script: .travis/deploy.sh $docker_org $tag $image_name
    on:
      branch: master
      tags: true
env:
  - JAVA_TAG=8 JAVA_VERSION=8u181-jdk-6 MAJOR_VERSION=3 MINOR_VERSION=5 PATCH_VERSION=4 BUILD_ARGS="JAVA_TAG JAVA_VERSION MAJOR_VERSION MINOR_VERSION PATCH_VERSION"
  - JAVA_TAG=10 JAVA_VERSION=10.0.2-jdk-6 MAJOR_VERSION=3 MINOR_VERSION=5 PATCH_VERSION=4 BUILD_ARGS="JAVA_TAG JAVA_VERSION MAJOR_VERSION MINOR_VERSION PATCH_VERSION"
